runtime: nodejs20

handlers:
  # Serve all static assets from the dist folder (after build)
  - url: /(.*\.(js|css|png|jpg|jpeg|svg|ico|json|txt|webp|woff|woff2))$
    static_files: dist/\1
    upload: dist/.*

  # SPA fallback — ALWAYS serve index.html for React Router
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
